# 这是一个 Yazi 文件管理器的键盘映射配置文件
# 使用 TOML 格式编写，可以通过 https://taplo.tamasfe.dev/ 等 TOML 工具验证
# 如果遇到问题，请到 https://github.com/yazi-rs/schemas 提交 issue

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager] # 文件管理器模式下的快捷键配置

keymap = [
    # 基本操作
    { on = "<Esc>", run = "escape", desc = "退出可视化模式/清除选择/取消搜索" },
    { on = "<C-[>", run = "escape", desc = "退出可视化模式/清除选择/取消搜索" },
    { on = "q", run = "quit", desc = "退出程序" },
    { on = "Q", run = "quit --no-cwd-file", desc = "退出程序但不保存当前目录" },
    { on = "<C-c>", run = "close", desc = "关闭当前标签页(如果是最后一个则退出)" },
    { on = "<C-z>", run = "suspend", desc = "挂起程序" },

    # 光标移动 - 垂直方向
    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },
    { on = "K", run = "arrow -5", desc = "光标上移" },
    { on = "J", run = "arrow 5", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    { on = "<S-PageUp>", run = "arrow -50%", desc = "上移半页" },
    { on = "<S-PageDown>", run = "arrow 50%", desc = "下移半页" },
    { on = "<PageUp>", run = "arrow -100%", desc = "上移一页" },
    { on = "<PageDown>", run = "arrow 100%", desc = "下移一页" },

    { on = [
        "g",
        "g",
    ], run = "arrow top", desc = "移动到顶部" },
    { on = "G", run = "arrow bot", desc = "移动到底部" },

    # 目录导航
    { on = "h", run = "leave", desc = "返回上级目录" },
    { on = "l", run = "enter", desc = "进入子目录" },

    { on = "<Left>", run = "leave", desc = "返回上级目录" },
    { on = "<Right>", run = "enter", desc = "进入子目录" },

    { on = "H", run = "back", desc = "返回上一个访问的目录" },
    { on = "L", run = "forward", desc = "前进到下一个访问的目录" },

    # 选择操作
    { on = "<Space>", run = [
        "toggle",
        "arrow 1",
    ], desc = "切换当前文件选择状态" },
    { on = "<C-a>", run = "toggle_all --state=on", desc = "全选所有文件" },
    { on = "<C-r>", run = "toggle_all", desc = "反选所有文件" },

    # 可视化模式
    { on = "v", run = "visual_mode", desc = "进入可视化选择模式" },
    { on = "V", run = "visual_mode --unset", desc = "进入可视化取消选择模式" },

    # 预览控制
    { on = "<C-u>", run = "seek -5", desc = "预览内容向上滚动5单位" },
    { on = "<C-d>", run = "seek 5", desc = "预览内容向下滚动5单位" },

    # 文件定位
    { on = "<Tab>", run = "spot", desc = "定位到当前悬停的文件" },

    # 文件操作
    { on = "o", run = "open", desc = "打开选中文件" },
    { on = "O", run = "open --interactive", desc = "交互式打开选中文件" },
    { on = "<Enter>", run = "open", desc = "打开选中文件" },
    { on = "<S-Enter>", run = "open --interactive", desc = "交互式打开选中文件" },
    { on = "y", run = "yank", desc = "复制选中文件" },
    { on = "x", run = "yank --cut", desc = "剪切选中文件" },
    { on = "p", run = "paste", desc = "粘贴文件" },
    { on = "P", run = "paste --force", desc = "强制粘贴(覆盖已存在文件)" },
    # { on = "-", run = "link", desc = "创建绝对路径符号链接" },
    # { on = "_", run = "link --relative", desc = "创建相对路径符号链接" },
    { on = "<C-->", run = "hardlink", desc = "创建硬链接" },
    { on = "Y", run = "unyank", desc = "取消复制/剪切状态" },
    { on = "X", run = "unyank", desc = "取消复制/剪切状态" },
    { on = "d", run = "remove", desc = "删除选中文件到回收站" },
    { on = "D", run = "remove --permanently", desc = "永久删除选中文件" },
    # { on = "a", run = "create", desc = "创建文件或目录(以/结尾)" },
    { on = "a", run = "rename --cursor=before_ext", desc = "重命名选中文件" },
    { on = "s", run = "shell --interactive", desc = "运行交互式shell命令" },
    { on = ":", run = "shell --block --interactive", desc = "运行阻塞式shell命令" },
    { on = ".", run = "hidden toggle", desc = "切换显示隐藏文件" },
    { on = "r", run = "search --via=fd", desc = "使用fd搜索文件名" },
    { on = "R", run = "search --via=rg", desc = "使用ripgrep搜索文件内容" },
    # { on = "<C-s>", run = "escape --search", desc = "取消当前搜索" },
    # { on = "z", run = "plugin zoxide", desc = "使用zoxide跳转目录" },
    { on = "Z", run = "plugin fzf", desc = "使用fzf跳转文件/目录" },

    # 显示模式
    { on = [
        "m",
        "s",
    ], run = "linemode size", desc = "显示模式: 文件大小" },
    { on = [
        "m",
        "p",
    ], run = "linemode permissions", desc = "显示模式: 权限" },
    { on = [
        "m",
        "b",
    ], run = "linemode btime", desc = "显示模式: 创建时间" },
    { on = [
        "m",
        "m",
    ], run = "linemode mtime", desc = "显示模式: 修改时间" },
    { on = [
        "m",
        "o",
    ], run = "linemode owner", desc = "显示模式: 所有者" },
    { on = [
        "m",
        "n",
    ], run = "linemode none", desc = "显示模式: 无" },

    # 复制路径信息
    { on = [
        "c",
        "c",
    ], run = "copy path", desc = "复制文件完整路径" },
    { on = [
        "c",
        "d",
    ], run = "copy dirname", desc = "复制所在目录路径" },
    { on = [
        "c",
        "f",
    ], run = "copy filename", desc = "复制文件名" },
    { on = [
        "c",
        "n",
    ], run = "copy name_without_ext", desc = "复制无扩展名的文件名" },

    # 文件过滤
    { on = "f", run = "filter --smart", desc = "智能过滤文件" },

    # 文件查找
    { on = "/", run = "find --smart", desc = "向下查找文件" },
    { on = "?", run = "find --previous --smart", desc = "向上查找文件" },
    { on = "-", run = "find_arrow", desc = "跳转到下一个匹配项" },
    { on = "_", run = "find_arrow --previous", desc = "跳转到上一个匹配项" },

    # 排序方式
    { on = [
        ",",
        "m",
    ], run = [
        "sort mtime --reverse=no",
        "linemode mtime",
    ], desc = "按修改时间排序" },
    { on = [
        ",",
        "M",
    ], run = [
        "sort mtime --reverse",
        "linemode mtime",
    ], desc = "按修改时间逆序排序" },
    { on = [
        ",",
        "b",
    ], run = [
        "sort btime --reverse=no",
        "linemode btime",
    ], desc = "按创建时间排序" },
    { on = [
        ",",
        "B",
    ], run = [
        "sort btime --reverse",
        "linemode btime",
    ], desc = "按创建时间逆序排序" },
    { on = [
        ",",
        "e",
    ], run = "sort extension --reverse=no", desc = "按扩展名排序" },
    { on = [
        ",",
        "E",
    ], run = "sort extension --reverse", desc = "按扩展名逆序排序" },
    { on = [
        ",",
        "a",
    ], run = "sort alphabetical --reverse=no", desc = "按字母顺序排序" },
    { on = [
        ",",
        "A",
    ], run = "sort alphabetical --reverse", desc = "按字母逆序排序" },
    { on = [
        ",",
        "n",
    ], run = "sort natural --reverse=no", desc = "按自然顺序排序" },
    { on = [
        ",",
        "N",
    ], run = "sort natural --reverse", desc = "按自然顺序逆序排序" },
    { on = [
        ",",
        "s",
    ], run = [
        "sort size --reverse=no",
        "linemode size",
    ], desc = "按文件大小排序" },
    { on = [
        ",",
        "S",
    ], run = [
        "sort size --reverse",
        "linemode size",
    ], desc = "按文件大小逆序排序" },
    { on = [
        ",",
        "r",
    ], run = "sort random --reverse=no", desc = "随机排序" },

    # 快速跳转
    { on = [
        "g",
        "h",
    ], run = "cd ~", desc = "跳转到家目录" },
    { on = [
        "g",
        "c",
    ], run = "cd ~/.config", desc = "跳转到配置目录" },
    { on = [
        "g",
        "d",
    ], run = "cd ~/Development", desc = "跳转到开发目录" },
    { on = [
        "g",
        "n",
    ], run = "cd ~/OneDrive", desc = "跳转到笔记目录" },
    { on = [
        "g",
        "<Space>",
    ], run = "cd --interactive", desc = "交互式跳转目录" },

    # 标签页操作
    { on = "t", run = "tab_create --current", desc = "使用当前目录创建新标签页" },

    { on = "1", run = "tab_switch 0", desc = "切换到第1个标签页" },
    { on = "2", run = "tab_switch 1", desc = "切换到第2个标签页" },
    { on = "3", run = "tab_switch 2", desc = "切换到第3个标签页" },
    { on = "4", run = "tab_switch 3", desc = "切换到第4个标签页" },
    { on = "5", run = "tab_switch 4", desc = "切换到第5个标签页" },
    { on = "6", run = "tab_switch 5", desc = "切换到第6个标签页" },
    { on = "7", run = "tab_switch 6", desc = "切换到第7个标签页" },
    { on = "8", run = "tab_switch 7", desc = "切换到第8个标签页" },
    { on = "9", run = "tab_switch 8", desc = "切换到第9个标签页" },

    { on = "[", run = "tab_switch -1 --relative", desc = "切换到上一个标签页" },
    { on = "]", run = "tab_switch 1 --relative", desc = "切换到下一个标签页" },

    { on = "{", run = "tab_swap -1", desc = "与上一个标签页交换位置" },
    { on = "}", run = "tab_swap 1", desc = "与下一个标签页交换位置" },

    # 任务管理
    { on = "w", run = "tasks_show", desc = "显示任务管理器" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[tasks] # 任务管理器模式下的快捷键配置
keymap = [
    { on = "<Esc>", run = "close", desc = "关闭任务管理器" },
    { on = "<C-[>", run = "close", desc = "关闭任务管理器" },
    { on = "<C-c>", run = "close", desc = "关闭任务管理器" },
    { on = "w", run = "close", desc = "关闭任务管理器" },

    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },
    { on = "K", run = "arrow -5", desc = "光标上移" },
    { on = "J", run = "arrow 5", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    { on = "<Enter>", run = "inspect", desc = "查看任务详情" },
    { on = "x", run = "cancel", desc = "取消任务" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[spot] # 文件定位模式下的快捷键配置
keymap = [
    { on = "<Esc>", run = "close", desc = "关闭定位模式" },
    { on = "<C-[>", run = "close", desc = "关闭定位模式" },
    { on = "<C-c>", run = "close", desc = "关闭定位模式" },
    { on = "<Tab>", run = "close", desc = "关闭定位模式" },

    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },
    { on = "K", run = "arrow -5", desc = "光标上移" },
    { on = "J", run = "arrow 5", desc = "光标下移" },
    { on = "h", run = "swipe -1", desc = "切换到上一个文件" },
    { on = "l", run = "swipe 1", desc = "切换到下一个文件" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },
    { on = "<Left>", run = "swipe -1", desc = "切换到下一个文件" },
    { on = "<Right>", run = "swipe 1", desc = "切换到上一个文件" },

    # 复制操作
    { on = ["c", "c"], run = "copy cell", desc = "复制选中单元格内容" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[pick] # 选择器模式下的快捷键配置
keymap = [
    { on = "<Esc>", run = "close", desc = "取消选择" },
    { on = "<C-[>", run = "close", desc = "取消选择" },
    { on = "<C-c>", run = "close", desc = "取消选择" },
    { on = "<Enter>", run = "close --submit", desc = "确认选择" },

    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },
    { on = "K", run = "arrow -5", desc = "光标上移" },
    { on = "J", run = "arrow 5", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[input] # 输入模式下的快捷键配置
keymap = [
    { on = "<C-c>", run = "close", desc = "取消输入" },
    { on = "<Enter>", run = "close --submit", desc = "确认输入" },
    { on = "<Esc>", run = "escape", desc = "返回普通模式或取消输入" },
    { on = "<C-[>", run = "escape", desc = "返回普通模式或取消输入" },

    # 模式切换
    { on = "i", run = "insert", desc = "进入插入模式" },
    { on = "I", run = [
        "move first-char",
        "insert",
    ], desc = "移动到行首并进入插入模式" },
    { on = "a", run = "insert --append", desc = "进入追加模式" },
    { on = "A", run = [
        "move eol",
        "insert --append",
    ], desc = "移动到行尾并进入追加模式" },
    { on = "v", run = "visual", desc = "进入可视化模式" },
    { on = "V", run = [
        "move bol",
        "visual",
        "move eol",
    ], desc = "进入可视化模式并全选" },
    { on = "r", run = "replace", desc = "替换单个字符" },

    # 字符移动
    { on = "h", run = "move -1", desc = "向左移动一个字符" },
    { on = "l", run = "move 1", desc = "向右移动一个字符" },
    { on = "<Left>", run = "move -1", desc = "向左移动一个字符" },
    { on = "<Right>", run = "move 1", desc = "向右移动一个字符" },
    { on = "<C-b>", run = "move -1", desc = "向左移动一个字符" },
    { on = "<C-f>", run = "move 1", desc = "向右移动一个字符" },

    # 单词移动
    { on = "b", run = "backward", desc = "移动到当前/前一个单词开头" },
    { on = "B", run = "backward --far", desc = "移动到当前/前一个WORD开头" },
    { on = "w", run = "forward", desc = "移动到下一个单词开头" },
    { on = "W", run = "forward --far", desc = "移动到下一个WORD开头" },
    { on = "e", run = "forward --end-of-word", desc = "移动到当前/下一个单词结尾" },
    { on = "E", run = "forward --far --end-of-word", desc = "移动到当前/下一个WORD结尾" },
    { on = "<A-b>", run = "backward", desc = "移动到当前/前一个单词开头" },
    { on = "<A-f>", run = "forward --end-of-word", desc = "移动到当前/下一个单词结尾" },

    # 行移动
    { on = "0", run = "move bol", desc = "移动到行首" },
    { on = "$", run = "move eol", desc = "移动到行尾" },
    { on = "_", run = "move first-char", desc = "移动到第一个非空白字符" },
    { on = "^", run = "move first-char", desc = "移动到第一个非空白字符" },
    { on = "<C-a>", run = "move bol", desc = "移动到行首" },
    { on = "<C-e>", run = "move eol", desc = "移动到行尾" },
    { on = "<Home>", run = "move bol", desc = "移动到行首" },
    { on = "<End>", run = "move eol", desc = "移动到行尾" },

    # 删除操作
    { on = "<Backspace>", run = "backspace", desc = "删除光标前字符" },
    { on = "<Delete>", run = "backspace --under", desc = "删除光标下字符" },
    { on = "<C-h>", run = "backspace", desc = "删除光标前字符" },
    { on = "<C-d>", run = "backspace --under", desc = "删除光标下字符" },

    # 整行删除
    { on = "<C-u>", run = "kill bol", desc = "删除到行首" },
    { on = "<C-k>", run = "kill eol", desc = "删除到行尾" },
    { on = "<C-w>", run = "kill backward", desc = "删除到当前单词开头" },
    { on = "<A-d>", run = "kill forward", desc = "删除到当前单词结尾" },

    # 剪切/复制/粘贴
    { on = "d", run = "delete --cut", desc = "剪切选中文本" },
    { on = "D", run = [
        "delete --cut",
        "move eol",
    ], desc = "剪切到行尾" },
    { on = "c", run = "delete --cut --insert", desc = "剪切选中文本并进入插入模式" },
    { on = "C", run = [
        "delete --cut --insert",
        "move eol",
    ], desc = "剪切到行尾并进入插入模式" },
    { on = "x", run = [
        "delete --cut",
        "move 1 --in-operating",
    ], desc = "剪切当前字符" },
    { on = "y", run = "yank", desc = "复制选中文本" },
    { on = "p", run = "paste", desc = "在光标后粘贴" },
    { on = "P", run = "paste --before", desc = "在光标前粘贴" },

    # 撤销/重做
    { on = "U", run = "undo", desc = "撤销操作" },
    { on = "<C-r>", run = "redo", desc = "重做操作" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[confirm] # 确认对话框模式下的快捷键配置
keymap = [
    { on = "<Esc>", run = "close", desc = "取消确认" },
    { on = "<C-[>", run = "close", desc = "取消确认" },
    { on = "<C-c>", run = "close", desc = "取消确认" },
    { on = "<Enter>", run = "close --submit", desc = "确认操作" },

    { on = "n", run = "close", desc = "取消确认" },
    { on = "y", run = "close --submit", desc = "确认操作" },

    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[cmp] # 自动补全模式下的快捷键配置
keymap = [
    { on = "<C-c>", run = "close", desc = "取消补全" },
    { on = "<Tab>", run = "close --submit", desc = "确认补全" },
    { on = "<Enter>", run = [
        "close --submit",
        "close_input --submit",
    ], desc = "确认补全并提交输入" },

    { on = "<A-k>", run = "arrow -1", desc = "光标上移" },
    { on = "<A-j>", run = "arrow 1", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    { on = "<C-p>", run = "arrow -1", desc = "光标上移" },
    { on = "<C-n>", run = "arrow 1", desc = "光标下移" },

    # 帮助
    { on = "~", run = "help", desc = "打开帮助" },
    { on = "<F1>", run = "help", desc = "打开帮助" },
]

[help] # 帮助模式下的快捷键配置
keymap = [
    { on = "<Esc>", run = "escape", desc = "清除过滤器或关闭帮助" },
    { on = "<C-[>", run = "escape", desc = "清除过滤器或关闭帮助" },
    { on = "<C-c>", run = "close", desc = "关闭帮助" },

    # 导航
    { on = "k", run = "arrow -1", desc = "光标上移" },
    { on = "j", run = "arrow 1", desc = "光标下移" },

    { on = "<Up>", run = "arrow -1", desc = "光标上移" },
    { on = "<Down>", run = "arrow 1", desc = "光标下移" },

    # 过滤
    { on = "f", run = "filter", desc = "过滤帮助项" },
]

[[manager.prepend_keymap]]
on = "S"
run = 'shell "$SHELL" --block'
desc = "在这里打开终端"
